name: lectures_env
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.11
  - pip
  - pip:
    - PyQt6==6.5.2
    - PyQt6-Qt6==6.5.2
    - PyQt6-sip==13.5.2
    - PySide6==6.5.2
    - matplotlib==3.7.2
    - numpy==1.25.2